### ISSUE TITLE
java.io.IOException: Corrupt key when using an encrypted Key

### ISSUE THREAD

**Issue by Beneter** [greenify/threema-decrypt#1]
When Threema is protected by a passphrase (at least on Android), the Key will be encrypted. Therefore the key.dat cannot be used by threema-decrypt right away, but needs to be decrypted first.
Currently threema-decrypt shows the following exception:
`Exception in thread "main" java.io.IOException: Corrupt key
	at cmg_clean.readKey(cmg_clean.java:63)
	at ThreemaDecrypt.main(ThreemaDecrypt.java:7)`

Unfortunately I am not able to guess the encryption-format, therefore I am stuck here. I will try AES-256-CBC encryption first. But do not know when I will find the time...

In the "Threema Cryptography Whitepaper" they write:

> AES-256-CBC encryption is applied to the private key before it’s written to the file. The key for this encryption is stored separately and can be protected using a passphrase [...].
> The key is randomly generated when the database is first created, and can be protected with a user-supplied passphrase (which is of course necessary if the user wishes to take advantage of this encryption). The passphrase is never written to permanent storage and therefore needs to be entered whenever the app process restarts [...].

**Comment by Beneter** [comment]
Unfortunately I was not able to decrypt key.dat with openssl:
`openssl aes-256-cbc -d -in key.dat -out key-unencrypted.dat`
aes-128-cbc, `-md sha256 / md5` and base64 encoded passphrase did not do the trick either.

Do you know what encryption format might be used?

**Comment by wilzbach** [comment]
I'm sorry. I don't have any extra information as I am not affiliated with Threema in any way.
Did you check their crypto white paper already?

**Comment by Beneter** [comment]
@wilzbach Thanks a lot for your work, your awesome blog-post and also your fast reply.

Yes I have read the Whitepaper but unfortunately they do not cover this topic in detail. So my best guess was, that they might be using the same cipher as for the private key (AES-256-CBC).
I have learned so far that NaCl (which Threema uses)  is writing a different format than OpenSSL. Therefore I should be using NaCl for decryption. For me the benefit  by no means justifies the effort needed to implement this.
Also I am missing the nonce which is probably needed for the decryption. At first I would need to reverse engineer Threema...

Again thanks a lot! You can close the issue if you want to.

**Comment by wilzbach** [comment]
I am glad you enjoyed the blog post!
No need to close the issue - I am interested in your progress. I just don't have much time to help out.

You could try writing the Threema Support. When I asked them for permission to publish this reverse engineering they were very fast with their approval.

**Comment by mrthaggar** [comment]
Any updates on this?

**Comment by Beneter** [comment]
@mrthaggar I did not follow up on this as for me the benefit by no means justifies the effort needed to implement this. Sorry and good luck!

**Comment by mrthaggar** [comment]
Thanks for the update.  I think in this case the problem is actually that Threema is now using SQLCipher version 4.2.0, so your parser is reporting 0 tables.  Any plans on updating?  Thanks

**Comment by wilzbach** [comment]
> Any plans on updating?

Not from my side. Sorry.
